name: quran_app
description: "Qur'an App"

#ini untuk mengantur versi dari aplikasi yang kita buat
version: 1.0.0+1


environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  get: ^4.6.6
  intl: ^0.19.0
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  flutter_bloc: ^8.1.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^8.0.0
  get_storage: ^2.1.1
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_launcher_icons: ^0.14.3
  shimmer: ^3.0.0
  firebase_crashlytics: ^4.3.3
  firebase_core: ^3.12.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_timezone: ^4.1.0
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.4.0
  timezone: ^0.10.0
  scrollable_positioned_list: ^0.3.8
  flutter_dotenv: ^5.2.1
  showcaseview: ^4.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/main_icon.png"
  adaptive_icon_background: "#FFFFFF"  # Warna background (untuk Android)
  adaptive_icon_foreground: "assets/images/main_icon.png"
  # min_sdk_android: 21


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sound/adzan.mp3
    - .env

